name: mottai_flutter_app_models
description: Models fro NPO MOTTAI matching app.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.17.5 <3.0.0'
  flutter: '>=3.0.3'

dependencies:
  cloud_firestore:
  cloud_functions:
  cupertino_icons:
  firebase_analytics:
  firebase_auth:
  firebase_core:
  firebase_messaging:
  firebase_storage:
  flutter:
    sdk: flutter
  freezed_annotation:
  hooks_riverpod:
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner:
  flutter_lints:
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable: ^6.3.1
  pedantic_mono:

flutter:
  uses-material-design: true
